//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UASBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightOrderTests
    {
        public int Id { get; set; }
        public int FlightOrderId { get; set; }
        public int TestId { get; set; }
        public Nullable<bool> Checked { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual FlightOrders FlightOrders { get; set; }
        public virtual Tests Tests { get; set; }
    }
}
