//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UASBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightOrders()
        {
            this.FlightEquipment = new HashSet<FlightEquipment>();
            this.FlightOrderTests = new HashSet<FlightOrderTests>();
            this.PilotReports = new HashSet<PilotReports>();
        }
    
        public int Id { get; set; }
        public System.DateTime FlightOrderDate { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public string FlightZoneFile { get; set; }
        public Nullable<int> MissionTypeId { get; set; }
        public int OrderedByUserId { get; set; }
        public Nullable<int> PilotUserId { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public Nullable<System.DateTime> ConditionDate { get; set; }
        public string AirSpace { get; set; }
        public string Weather { get; set; }
        public string Temperature { get; set; }
        public string Wind { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> AnountOfPictures { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightEquipment> FlightEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightOrderTests> FlightOrderTests { get; set; }
        public virtual MissionTypes MissionTypes { get; set; }
        public virtual Operators Operators { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PilotReports> PilotReports { get; set; }
    }
}
