//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UASBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceLog
    {
        public int Id { get; set; }
        public System.DateTime ReportDate { get; set; }
        public int ReportedByUserId { get; set; }
        public int EquipmentId { get; set; }
        public int PartId { get; set; }
        public string Description { get; set; }
        public Nullable<int> RepairedByUserId { get; set; }
        public Nullable<System.DateTime> RepairDate { get; set; }
        public string MeasureDescription { get; set; }
    
        public virtual Equipments Equipments { get; set; }
        public virtual Parts Parts { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
