//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UASBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tests()
        {
            this.FlightOrderTests = new HashSet<FlightOrderTests>();
            this.PilotReports = new HashSet<PilotReports>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TestGroupId { get; set; }
        public string Test { get; set; }
        public Nullable<int> PartId { get; set; }
        public string Help { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightOrderTests> FlightOrderTests { get; set; }
        public virtual Parts Parts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PilotReports> PilotReports { get; set; }
        public virtual TestGroups TestGroups { get; set; }
    }
}
