//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UASBase.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UASDataEntities : DbContext
    {
        public UASDataEntities()
            : base("name=UASDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equipments> Equipments { get; set; }
        public virtual DbSet<FlightEquipment> FlightEquipment { get; set; }
        public virtual DbSet<FlightOrders> FlightOrders { get; set; }
        public virtual DbSet<FlightOrderTests> FlightOrderTests { get; set; }
        public virtual DbSet<MissionTypes> MissionTypes { get; set; }
        public virtual DbSet<Operators> Operators { get; set; }
        public virtual DbSet<Parts> Parts { get; set; }
        public virtual DbSet<PilotReports> PilotReports { get; set; }
        public virtual DbSet<ServiceLog> ServiceLog { get; set; }
        public virtual DbSet<TestGroups> TestGroups { get; set; }
        public virtual DbSet<Tests> Tests { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
